{"version":1,"ops":[{"type":3,"author":{"id":"5ff63cc106aa5ba7b893d7126eb025e41b25a791"},"timestamp":1534966987,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTE1NTQxNQ==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415155415"},"message":"Was there also a file named `df-ai-debug.log`?","files":null},{"type":3,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1534967352,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTE1NzA5OQ==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415157099"},"message":"Unfortunately no, not for this issue.","files":null},{"type":3,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1534977894,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTIwNzc4Nw==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415207787"},"message":"is there a custom build I could run to pull more detail?","files":null},{"type":5,"author":{"id":"5ff63cc106aa5ba7b893d7126eb025e41b25a791"},"timestamp":1534978198,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDE4MDM5MDIxNjE="},"added":["bug"],"removed":[]},{"type":5,"author":{"id":"5ff63cc106aa5ba7b893d7126eb025e41b25a791"},"timestamp":1534978198,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDE4MDM5MDIxNjQ="},"added":["crash"],"removed":[]},{"type":3,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1534978687,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTIxMjk5MA==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415212990"},"message":"https://clips.twitch.tv/GlutenFreeSlipperyPuffinPeoplesChamp","files":null},{"type":6,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1534978687,"metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdDEyMjE5MDM3Mg=="},"target":"57093aabf225d895c8b82089696edd8e543920af1c381ee7a2528a09609571fa","message":"https://clips.twitch.tv/GlutenFreeSlipperyPuffinPeoplesChamp\n\n[stderr.log](https://github.com/BenLubar/df-ai/files/2312250/stderr.log)\n[gamelog.txt](https://github.com/BenLubar/df-ai/files/2312251/gamelog.txt)\n[df-ai.log](https://github.com/BenLubar/df-ai/files/2312252/df-ai.log)","files":null},{"type":3,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1534987643,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTI0NTI0Mw==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415245243"},"message":"Removed blueprints folder, activating legacy mode. Crash still occurs.  So, unrelated to \"blueprints\"","files":null},{"type":3,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1535034246,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQxNTQzNDA3OA==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-415434078"},"message":"This morning I redownloaded the latest from [buildmaster (180821000)](https://buildmaster.lubar.me/applications/2/builds/build?releaseNumber=dfhack-0.44.12-r1\u0026buildNumber=180821000) and it seems to be working.  \n\nSoooooo, maybe this is just a one-off issue?\n\nClose for now?","files":null},{"type":4,"author":{"id":"c6a8cb5364bc3aec41d25e1ee1093680e858789c"},"timestamp":1535036790,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MTgwNTUzNjM0NQ=="},"status":2},{"type":3,"author":{"id":"266174861d6de54ac1133278150d49dd13c41719"},"timestamp":1559860943,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ5OTY5NDU3Ng==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-499694576"},"message":"The reporter should maybe not have closed this. In the latest release, I am able to reproduce exactly the same behavior, in particular this message upon encountering a trade:\n\n[trade] Unexpected viewscreen. Bailing.\n\n[df-ai.log](https://github.com/BenLubar/df-ai/files/3263760/df-ai.log)\n[df-ai-debug.log](https://github.com/BenLubar/df-ai/files/3263762/df-ai-debug.log)\n\nHowever the contents of df-ai-debug.log appear to be related to an earlier, non-fatal error having to do with customizing a squad whose units could not be found.","files":null},{"type":3,"author":{"id":"5ca0b7fd5f24e5c8e6d762c63b4926d0b1edb1a0"},"timestamp":1559870565,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDQ5OTcyNjQxMg==","github-url":"https://github.com/BenLubar/df-ai/issues/64#issuecomment-499726412"},"message":"Can you get rid of the debug log and allow it to be recreated when this issue occurs just to make sure that message isn't relevant?","files":null},{"type":4,"author":{"id":"5ff63cc106aa5ba7b893d7126eb025e41b25a791"},"timestamp":1559918959,"metadata":{"github-id":"MDEzOlJlb3BlbmVkRXZlbnQyMzk3NTE3ODgw"},"status":1}]}